// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// geodistpar_cpp
NumericMatrix geodistpar_cpp(NumericMatrix x, NumericMatrix y, int measure);
RcppExport SEXP _geodistpar_geodistpar_cpp(SEXP xSEXP, SEXP ySEXP, SEXP measureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type measure(measureSEXP);
    rcpp_result_gen = Rcpp::wrap(geodistpar_cpp(x, y, measure));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geodistpar_geodistpar_cpp", (DL_FUNC) &_geodistpar_geodistpar_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_geodistpar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
