# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geodistpar_cpp <- function(x, y, measure) {
    .Call('_geodistpar_geodistpar_cpp', PACKAGE = 'geodistpar', x, y, measure)
}

